[2024-10-15 09:42:56,684.684] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 09:43:01,545.545] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 09:43:01,548.548] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 09:43:24,923.923] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 09:43:25,220.220] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 09:43:29,968.968] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 09:43:29,972.972] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:03:40,707.707] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:03:41,083.083] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:03:45,975.975] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:03:45,978.978] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:04:08,257.257] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:04:08,595.595] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:04:13,220.220] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:04:13,223.223] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:04:23,956.956] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:04:24,277.277] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:04:28,839.839] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:04:28,842.842] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:07:17,907.907] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:07:18,228.228] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:07:22,754.754] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:07:22,757.757] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:09:52,504.504] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:09:52,835.835] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:09:57,969.969] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:09:57,972.972] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:10:01,679.679] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:10:02,007.007] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:10:06,744.744] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:10:06,749.749] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:10:12,945.945] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:10:13,271.271] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:10:18,250.250] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:10:18,253.253] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:10:26,707.707] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:10:27,028.028] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:10:31,889.889] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:10:31,892.892] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:20:51,317.317] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-10-15 10:20:51,317.317] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-10-15 10:20:51,319.319] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-10-15 10:20:51,319.319] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-10-15 10:20:51,319.319] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-10-15 10:20:51,319.319] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-10-15 10:20:51,320.320] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 10:20:51,321.321] base.py -> _exec_single_context line:1903 [INFO]: SELECT dataset.id AS dataset_id, dataset.account_id AS dataset_account_id, dataset.name AS dataset_name, dataset.icon AS dataset_icon, dataset.description AS dataset_description, dataset.updated_at AS dataset_updated_at, dataset.created_at AS dataset_created_at 
FROM dataset 
WHERE dataset.id = %(pk_1)s::UUID
[2024-10-15 10:20:51,321.321] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00013s] {'pk_1': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89')}
[2024-10-15 10:20:51,323.323] base.py -> _exec_single_context line:1903 [INFO]: SELECT upload_file.id AS upload_file_id, upload_file.account_id AS upload_file_account_id, upload_file.name AS upload_file_name, upload_file.key AS upload_file_key, upload_file.size AS upload_file_size, upload_file.extension AS upload_file_extension, upload_file.mime_type AS upload_file_mime_type, upload_file.hash AS upload_file_hash, upload_file.updated_at AS upload_file_updated_at, upload_file.created_at AS upload_file_created_at 
FROM upload_file 
WHERE upload_file.account_id = %(account_id_1)s::UUID AND upload_file.id IN (%(id_1_1)s::UUID)
[2024-10-15 10:20:51,323.323] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00016s] {'account_id_1': '46db30d1-3199-4e79-a0cd-abf12fa6858f', 'id_1_1': '1f913c05-8783-4de4-a2c7-c551fa17d0f6'}
[2024-10-15 10:20:51,325.325] base.py -> _exec_single_context line:1903 [INFO]: INSERT INTO process_rule (account_id, dataset_id, mode, rule) VALUES (%(account_id)s::UUID, %(dataset_id)s::UUID, %(mode)s, %(rule)s) RETURNING process_rule.id, process_rule.updated_at, process_rule.created_at
[2024-10-15 10:20:51,325.325] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00015s] {'account_id': '46db30d1-3199-4e79-a0cd-abf12fa6858f', 'dataset_id': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89'), 'mode': 'automatic', 'rule': '{"pre_process_rules": [{"id": "remove_extra_space", "enabled": true}, {"id": "remove_url_and_email", "enabled": true}], "segment": {"separators": ["\ ... (15 characters truncated) ... "\\u3002|\\uff01|\\uff1f", "\\\\.\\\\s|\\\\!\\\\s|\\\\?\\\\s", "\\uff1b|;\\\\s", "\\uff0c|,\\\\s", " ", ""], "chunk_size": 500, "chunk_overlap": 50}}'}
[2024-10-15 10:20:51,326.326] base.py -> _commit_impl line:1146 [INFO]: COMMIT
[2024-10-15 10:20:51,349.349] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 10:20:51,352.352] base.py -> _exec_single_context line:1903 [INFO]: SELECT document.id AS document_id, document.account_id AS document_account_id, document.dataset_id AS document_dataset_id, document.upload_file_id AS document_upload_file_id, document.process_rule_id AS document_process_rule_id, document.batch AS document_batch, document.name AS document_name, document.position AS document_position, document.character_count AS document_character_count, document.token_count AS document_token_count, document.processing_started_at AS document_processing_started_at, document.parsing_completed_at AS document_parsing_completed_at, document.splitting_completed_at AS document_splitting_completed_at, document.indexing_completed_at AS document_indexing_completed_at, document.completed_at AS document_completed_at, document.stopped_at AS document_stopped_at, document.error AS document_error, document.enabled AS document_enabled, document.disabled_at AS document_disabled_at, document.status AS document_status, document.updated_at AS document_updated_at, document.created_at AS document_created_at 
FROM document 
WHERE document.dataset_id = %(dataset_id_1)s::UUID ORDER BY document.position DESC 
 LIMIT %(param_1)s
[2024-10-15 10:20:51,352.352] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00022s] {'dataset_id_1': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89'), 'param_1': 1}
[2024-10-15 10:20:51,354.354] base.py -> _exec_single_context line:1903 [INFO]: SELECT upload_file.id AS upload_file_id, upload_file.account_id AS upload_file_account_id, upload_file.name AS upload_file_name, upload_file.key AS upload_file_key, upload_file.size AS upload_file_size, upload_file.extension AS upload_file_extension, upload_file.mime_type AS upload_file_mime_type, upload_file.hash AS upload_file_hash, upload_file.updated_at AS upload_file_updated_at, upload_file.created_at AS upload_file_created_at 
FROM upload_file 
WHERE upload_file.id = %(pk_1)s::UUID
[2024-10-15 10:20:51,354.354] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00016s] {'pk_1': UUID('1f913c05-8783-4de4-a2c7-c551fa17d0f6')}
[2024-10-15 10:20:51,355.355] base.py -> _exec_single_context line:1903 [INFO]: SELECT process_rule.id AS process_rule_id, process_rule.account_id AS process_rule_account_id, process_rule.dataset_id AS process_rule_dataset_id, process_rule.mode AS process_rule_mode, process_rule.rule AS process_rule_rule, process_rule.updated_at AS process_rule_updated_at, process_rule.created_at AS process_rule_created_at 
FROM process_rule 
WHERE process_rule.id = %(pk_1)s::UUID
[2024-10-15 10:20:51,355.355] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00014s] {'pk_1': UUID('d376db57-3e72-4f49-9d29-b7dc1fa984f1')}
[2024-10-15 10:20:51,357.357] base.py -> _exec_single_context line:1903 [INFO]: INSERT INTO document (account_id, dataset_id, upload_file_id, process_rule_id, batch, name, position, processing_started_at, parsing_completed_at, splitting_completed_at, indexing_completed_at, completed_at, stopped_at, disabled_at) VALUES (%(account_id)s::UUID, %(dataset_id)s::UUID, %(upload_file_id)s::UUID, %(process_rule_id)s::UUID, %(batch)s, %(name)s, %(position)s, %(processing_started_at)s, %(parsing_completed_at)s, %(splitting_completed_at)s, %(indexing_completed_at)s, %(completed_at)s, %(stopped_at)s, %(disabled_at)s) RETURNING document.id, document.character_count, document.token_count, document.error, document.enabled, document.status, document.updated_at, document.created_at
[2024-10-15 10:20:51,357.357] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00016s] {'account_id': '46db30d1-3199-4e79-a0cd-abf12fa6858f', 'dataset_id': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89'), 'upload_file_id': UUID('1f913c05-8783-4de4-a2c7-c551fa17d0f6'), 'process_rule_id': UUID('d376db57-3e72-4f49-9d29-b7dc1fa984f1'), 'batch': '20241015102051510113', 'name': 'LLMOps 项目提示词大全.md', 'position': 104, 'processing_started_at': None, 'parsing_completed_at': None, 'splitting_completed_at': None, 'indexing_completed_at': None, 'completed_at': None, 'stopped_at': None, 'disabled_at': None}
[2024-10-15 10:20:51,357.357] base.py -> _commit_impl line:1146 [INFO]: COMMIT
[2024-10-15 10:20:51,375.375] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 10:20:51,376.376] base.py -> _exec_single_context line:1903 [INFO]: SELECT document.id AS document_id, document.account_id AS document_account_id, document.dataset_id AS document_dataset_id, document.upload_file_id AS document_upload_file_id, document.process_rule_id AS document_process_rule_id, document.batch AS document_batch, document.name AS document_name, document.position AS document_position, document.character_count AS document_character_count, document.token_count AS document_token_count, document.processing_started_at AS document_processing_started_at, document.parsing_completed_at AS document_parsing_completed_at, document.splitting_completed_at AS document_splitting_completed_at, document.indexing_completed_at AS document_indexing_completed_at, document.completed_at AS document_completed_at, document.stopped_at AS document_stopped_at, document.error AS document_error, document.enabled AS document_enabled, document.disabled_at AS document_disabled_at, document.status AS document_status, document.updated_at AS document_updated_at, document.created_at AS document_created_at 
FROM document 
WHERE document.id = %(pk_1)s::UUID
[2024-10-15 10:20:51,376.376] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00018s] {'pk_1': UUID('b5c4851e-8e4c-4eb6-99d9-50f2ab207b5f')}
[2024-10-15 10:20:51,411.411] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-10-15 10:20:51,411.411] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 10:20:51] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-10-15 10:48:45,564.564] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:48:45,949.949] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:48:50,799.799] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:48:50,803.803] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:49:02,675.675] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:49:02,999.999] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:49:07,803.803] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:49:07,806.806] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:49:09,231.231] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:49:09,552.552] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:49:14,261.261] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:49:14,264.264] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:55:31,714.714] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:55:32,010.010] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:55:36,655.655] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:55:36,659.659] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:55:53,115.115] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:55:53,426.426] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:55:57,892.892] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:55:57,895.895] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 10:56:20,123.123] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 10:56:20,420.420] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 10:56:25,068.068] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 10:56:25,071.071] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:07:09,034.034] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:07:09,369.369] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:07:13,701.701] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:07:13,703.703] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:07:19,805.805] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:07:20,109.109] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:07:24,877.877] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:07:24,880.880] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:07:27,406.406] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:07:27,772.772] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:07:32,194.194] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:07:32,197.197] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:27:52,434.434] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:27:52,794.794] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:27:57,483.483] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:27:57,486.486] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:30:20,847.847] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:30:21,159.159] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:30:25,619.619] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:30:25,622.622] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:30:30,600.600] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:30:30,971.971] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:30:35,543.543] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:30:35,547.547] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:30:36,970.970] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:30:37,331.331] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:30:43,417.417] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:30:43,420.420] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:34:30,523.523] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:34:30,936.936] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:34:35,233.233] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:34:35,235.235] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:34:45,311.311] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:34:45,683.683] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:34:49,937.937] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:34:49,939.939] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:40:53,366.366] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:40:53,661.661] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:40:58,875.875] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:40:58,878.878] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:43:16,172.172] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:43:16,490.490] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:43:21,318.318] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:43:21,322.322] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:43:22,784.784] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:43:23,101.101] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:43:27,926.926] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:43:27,929.929] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:43:39,807.807] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:43:40,100.100] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:43:45,519.519] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:43:45,522.522] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 11:45:37,411.411] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 11:45:37,771.771] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 11:45:42,292.292] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 11:45:42,295.295] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:20:49,630.630] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-10-15 14:20:50,023.023] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:20:54,575.575] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:20:54,578.578] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:25:16,733.733] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-10-15 14:25:17,076.076] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:25:21,727.727] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:25:21,730.730] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:54:57,989.989] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 14:54:58,333.333] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:55:03,133.133] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:55:03,136.136] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:55:06,878.878] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 14:55:07,258.258] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:55:11,905.905] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:55:11,909.909] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:55:40,060.060] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 14:55:40,350.350] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:55:44,965.965] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:55:44,968.968] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:55:47,547.547] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 14:55:47,884.884] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:55:52,345.345] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:55:52,347.347] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:56:12,216.216] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 14:56:12,554.554] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:56:17,254.254] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:56:17,257.257] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:57:09,535.535] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 14:57:09,889.889] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:57:14,618.618] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:57:14,620.620] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:58:18,565.565] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 14:58:18,889.889] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:58:21,483.483] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:58:24,034.034] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:58:36,328.328] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:58:45,374.374] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:58:52,241.241] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:58:56,930.930] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:59:11,337.337] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:59:12,764.764] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:59:17,603.603] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:59:27,683.683] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:59:32,333.333] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:59:32,336.336] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 14:59:43,033.033] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 14:59:43,367.367] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 14:59:47,887.887] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 14:59:47,890.890] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:00:39,949.949] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:00:40,261.261] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:00:44,751.751] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:00:44,754.754] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:00:50,818.818] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:00:51,170.170] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:00:55,768.768] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:00:55,772.772] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:01:09,846.846] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:01:10,138.138] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:14,965.965] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:19,683.683] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:27,638.638] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:31,233.233] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:34,874.874] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:39,584.584] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:01:44,181.181] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:01:44,184.184] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:02:01,753.753] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:02:02,065.065] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:02:06,472.472] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:02:06,475.475] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:02:40,225.225] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:02:40,521.521] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:02:45,107.107] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:02:45,110.110] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:02:51,210.210] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:02:51,495.495] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:02:56,167.167] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:02:56,170.170] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:03:02,191.191] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:03:02,510.510] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:03:07,058.058] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:03:07,060.060] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:03:09,647.647] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:03:09,985.985] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:03:14,807.807] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:03:14,809.809] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:03:17,372.372] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:03:17,700.700] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:03:22,066.066] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:03:22,067.067] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:03:40,905.905] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:03:41,215.215] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:03:45,842.842] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:03:45,845.845] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:04:01,217.217] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:04:01,536.536] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:04:06,414.414] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:04:06,417.417] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:04:40,199.199] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:04:40,535.535] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:05:02,630.630] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:05:07,261.261] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:05:07,264.264] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:05:23,764.764] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:05:24,077.077] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:05:34,590.590] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:05:39,051.051] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:05:39,054.054] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:05:57,918.918] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\pkg\\response\\response.py', reloading
[2024-10-15 15:05:58,254.254] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:06:02,910.910] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:06:02,912.912] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:06:10,106.106] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\lib\\helper.py', reloading
[2024-10-15 15:06:10,425.425] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:06:15,306.306] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:06:15,309.309] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:09:36,546.546] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:09:36,916.916] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:09:41,380.380] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:09:41,382.382] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:11:19,644.644] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:11:19,963.963] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:11:24,461.461] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:11:24,464.464] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:11:28,238.238] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:11:28,597.597] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:11:33,172.172] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:11:33,176.176] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:11:36,907.907] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:11:37,216.216] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:11:41,539.539] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:11:41,542.542] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:11:56,846.846] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:11:57,191.191] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:12:01,508.508] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:12:01,511.511] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:13:29,328.328] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:13:29,648.648] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:13:34,300.300] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:13:34,303.303] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:13:35,759.759] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:13:36,072.072] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:13:40,714.714] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:13:40,717.717] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:14:01,742.742] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:14:02,069.069] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:14:06,885.885] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:14:06,888.888] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:14:10,652.652] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:14:10,947.947] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:14:15,639.639] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:14:15,642.642] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:14:31,097.097] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:14:31,422.422] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:14:36,055.055] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:14:36,058.058] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:14:43,282.282] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:14:43,666.666] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:14:48,436.436] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:14:48,439.439] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:15:30,436.436] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:15:30,741.741] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:15:35,445.445] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:15:35,448.448] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 15:15:51,940.940] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 15:15:52,286.286] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 15:15:56,890.890] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 15:15:56,893.893] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:10:47,267.267] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 16:10:47,692.692] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:10:52,568.568] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:10:52,571.571] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:11:01,083.083] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 16:11:01,404.404] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:11:06,270.270] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:11:06,273.273] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:11:12,334.334] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 16:11:12,638.638] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:11:17,329.329] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:11:17,332.332] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:11:29,183.183] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\model\\conversation.py', reloading
[2024-10-15 16:11:29,615.615] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:11:34,663.663] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:11:34,666.666] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:12:00,501.501] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\conversation_entity.py', reloading
[2024-10-15 16:12:00,798.798] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:12:05,947.947] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:12:05,949.949] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:13:48,138.138] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\conversation_entity.py', reloading
[2024-10-15 16:13:48,442.442] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:13:53,114.114] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:13:53,117.117] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:14:11,940.940] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\conversation_entity.py', reloading
[2024-10-15 16:14:12,267.267] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:14:16,929.929] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:14:16,932.932] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 16:17:51,511.511] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\conversation_entity.py', reloading
[2024-10-15 16:17:51,820.820] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 16:17:56,612.612] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 16:17:56,615.615] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 17:36:45,091.091] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-10-15 17:36:45,092.092] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-10-15 17:36:45,094.094] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-10-15 17:36:45,095.095] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-10-15 17:36:45,097.097] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-10-15 17:36:45,097.097] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-10-15 17:36:45,100.100] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 17:36:45,103.103] base.py -> _exec_single_context line:1903 [INFO]: SELECT dataset.id AS dataset_id, dataset.account_id AS dataset_account_id, dataset.name AS dataset_name, dataset.icon AS dataset_icon, dataset.description AS dataset_description, dataset.updated_at AS dataset_updated_at, dataset.created_at AS dataset_created_at 
FROM dataset 
WHERE dataset.id = %(pk_1)s::UUID
[2024-10-15 17:36:45,104.104] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00030s] {'pk_1': UUID('47d727ee-e222-489f-8ee3-88e730457b22')}
[2024-10-15 17:36:45,105.105] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\dataset_handler.py", line 54, in hit
    hit_result = self.dataset_service.hit(dataset_id, req)
  File "D:\Code\llmops\llmops-api\internal\service\dataset_service.py", line 154, in hit
    raise NotFoundException("该知识库不存在")
internal.exception.exception.NotFoundException
[2024-10-15 17:36:45,109.109] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-10-15 17:36:45,110.110] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 17:36:45] "POST /datasets/47d727ee-e222-489f-8ee3-88e730457b22/hit HTTP/1.1" 200 -
[2024-10-15 17:36:51,083.083] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 17:36:51,083.083] base.py -> _exec_single_context line:1903 [INFO]: SELECT dataset.id AS dataset_id, dataset.account_id AS dataset_account_id, dataset.name AS dataset_name, dataset.icon AS dataset_icon, dataset.description AS dataset_description, dataset.updated_at AS dataset_updated_at, dataset.created_at AS dataset_created_at 
FROM dataset 
WHERE dataset.id = %(pk_1)s::UUID
[2024-10-15 17:36:51,083.083] base.py -> _exec_single_context line:1908 [INFO]: [cached since 5.98s ago] {'pk_1': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89')}
[2024-10-15 17:36:51,086.086] base.py -> _exec_single_context line:1903 [INFO]: SELECT dataset.id AS dataset_id, dataset.account_id AS dataset_account_id, dataset.name AS dataset_name, dataset.icon AS dataset_icon, dataset.description AS dataset_description, dataset.updated_at AS dataset_updated_at, dataset.created_at AS dataset_created_at 
FROM dataset 
WHERE dataset.id IN (%(id_1_1)s::UUID) AND dataset.account_id = %(account_id_1)s::UUID
[2024-10-15 17:36:51,087.087] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00030s] {'account_id_1': '46db30d1-3199-4e79-a0cd-abf12fa6858f', 'id_1_1': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89')}
[2024-10-15 17:36:53,071.071] __init__.py -> initialize line:113 [DEBUG]: Building prefix dict from the default dictionary ...
[2024-10-15 17:36:53,071.071] __init__.py -> initialize line:132 [DEBUG]: Loading model from cache C:\Users\Administrator\AppData\Local\Temp\jieba.cache
[2024-10-15 17:36:53,669.669] __init__.py -> initialize line:164 [DEBUG]: Loading model cost 0.598 seconds.
[2024-10-15 17:36:53,669.669] __init__.py -> initialize line:166 [DEBUG]: Prefix dict has been built successfully.
[2024-10-15 17:36:53,672.672] base.py -> _exec_single_context line:1903 [INFO]: SELECT keyword_table.keyword_table AS keyword_table_keyword_table 
FROM keyword_table 
WHERE keyword_table.dataset_id IN (%(dataset_id_1_1)s::UUID)
[2024-10-15 17:36:53,672.672] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00033s] {'dataset_id_1_1': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89')}
[2024-10-15 17:36:53,683.683] base.py -> _exec_single_context line:1903 [INFO]: SELECT segment.id AS segment_id, segment.account_id AS segment_account_id, segment.dataset_id AS segment_dataset_id, segment.document_id AS segment_document_id, segment.node_id AS segment_node_id, segment.position AS segment_position, segment.content AS segment_content, segment.character_count AS segment_character_count, segment.token_count AS segment_token_count, segment.keywords AS segment_keywords, segment.hash AS segment_hash, segment.hit_count AS segment_hit_count, segment.enabled AS segment_enabled, segment.disabled_at AS segment_disabled_at, segment.processing_started_at AS segment_processing_started_at, segment.indexing_completed_at AS segment_indexing_completed_at, segment.completed_at AS segment_completed_at, segment.stopped_at AS segment_stopped_at, segment.error AS segment_error, segment.status AS segment_status, segment.updated_at AS segment_updated_at, segment.created_at AS segment_created_at 
FROM segment 
WHERE segment.id IN (%(id_1_1)s::UUID, %(id_1_2)s::UUID, %(id_1_3)s::UUID, %(id_1_4)s::UUID, %(id_1_5)s::UUID, %(id_1_6)s::UUID, %(id_1_7)s::UUID, %(id_1_8)s::UUID, %(id_1_9)s::UUID, %(id_1_10)s::UUID)
[2024-10-15 17:36:53,683.683] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00037s] {'id_1_1': '74bf1917-750c-4442-93f6-8f7b32ca58bd', 'id_1_2': '59b73969-23cc-43d3-8ff5-dddabd578635', 'id_1_3': '95e47e06-d6e4-434c-820b-32d04efa58c8', 'id_1_4': '6ba19757-a987-4622-977c-782067d59787', 'id_1_5': '1269b4d4-109d-4d91-a496-aa9511797876', 'id_1_6': 'e22a6121-cb1e-49b0-9bb1-e14d64cd5f72', 'id_1_7': 'd715c72a-ba2a-4d05-ba9b-3054f0d33887', 'id_1_8': '5bb91122-56f7-4eb5-956f-ef5e06638572', 'id_1_9': '69f2fe4d-06f2-45cf-a61a-e628c6eb270b', 'id_1_10': 'ae52f7b3-90aa-4cc6-9dae-71b25cf53899'}
[2024-10-15 17:36:53,688.688] base.py -> _exec_single_context line:1903 [INFO]: INSERT INTO dataset_query (dataset_id, query, source, source_app_id, created_by) VALUES (%(dataset_id)s::UUID, %(query)s, %(source)s, %(source_app_id)s::UUID, %(created_by)s::UUID) RETURNING dataset_query.id, dataset_query.updated_at, dataset_query.created_at
[2024-10-15 17:36:53,688.688] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00028s] {'dataset_id': UUID('f3f28f75-8e60-4eba-b6df-4d1b390bbd89'), 'query': '想学习flask，有什么建议么？', 'source': <RetrievalSource.HIT_TESTING: 'hit_testing'>, 'source_app_id': None, 'created_by': '46db30d1-3199-4e79-a0cd-abf12fa6858f'}
[2024-10-15 17:36:53,690.690] base.py -> _commit_impl line:1146 [INFO]: COMMIT
[2024-10-15 17:36:53,692.692] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 17:36:53,693.693] base.py -> _exec_single_context line:1903 [INFO]: INSERT INTO dataset_query (dataset_id, query, source, source_app_id, created_by) VALUES (%(dataset_id)s::UUID, %(query)s, %(source)s, %(source_app_id)s::UUID, %(created_by)s::UUID) RETURNING dataset_query.id, dataset_query.updated_at, dataset_query.created_at
[2024-10-15 17:36:53,693.693] base.py -> _exec_single_context line:1908 [INFO]: [cached since 0.004843s ago] {'dataset_id': 'f3f28f75-8e60-4eba-b6df-4d1b390bbd89', 'query': '想学习flask，有什么建议么？', 'source': <RetrievalSource.HIT_TESTING: 'hit_testing'>, 'source_app_id': None, 'created_by': '46db30d1-3199-4e79-a0cd-abf12fa6858f'}
[2024-10-15 17:36:53,694.694] base.py -> _commit_impl line:1146 [INFO]: COMMIT
[2024-10-15 17:36:53,696.696] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 17:36:53,697.697] base.py -> _exec_single_context line:1903 [INFO]: UPDATE segment SET hit_count=(segment.hit_count + %(hit_count_1)s) WHERE segment.id IN (%(id_1_1)s::UUID, %(id_1_2)s::UUID)
[2024-10-15 17:36:53,697.697] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00033s] {'hit_count_1': 1, 'id_1_1': UUID('1ffa713d-b538-4f92-9de9-f169aae60d90'), 'id_1_2': '74bf1917-750c-4442-93f6-8f7b32ca58bd'}
[2024-10-15 17:36:53,698.698] base.py -> _commit_impl line:1146 [INFO]: COMMIT
[2024-10-15 17:36:53,700.700] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-10-15 17:36:53,700.700] base.py -> _exec_single_context line:1903 [INFO]: SELECT segment.id AS segment_id, segment.account_id AS segment_account_id, segment.dataset_id AS segment_dataset_id, segment.document_id AS segment_document_id, segment.node_id AS segment_node_id, segment.position AS segment_position, segment.content AS segment_content, segment.character_count AS segment_character_count, segment.token_count AS segment_token_count, segment.keywords AS segment_keywords, segment.hash AS segment_hash, segment.hit_count AS segment_hit_count, segment.enabled AS segment_enabled, segment.disabled_at AS segment_disabled_at, segment.processing_started_at AS segment_processing_started_at, segment.indexing_completed_at AS segment_indexing_completed_at, segment.completed_at AS segment_completed_at, segment.stopped_at AS segment_stopped_at, segment.error AS segment_error, segment.status AS segment_status, segment.updated_at AS segment_updated_at, segment.created_at AS segment_created_at 
FROM segment 
WHERE segment.id IN (%(id_1_1)s::UUID, %(id_1_2)s::UUID)
[2024-10-15 17:36:53,701.701] base.py -> _exec_single_context line:1908 [INFO]: [cached since 0.01757s ago] {'id_1_1': '1ffa713d-b538-4f92-9de9-f169aae60d90', 'id_1_2': '74bf1917-750c-4442-93f6-8f7b32ca58bd'}
[2024-10-15 17:36:53,705.705] base.py -> _exec_single_context line:1903 [INFO]: SELECT document.id AS document_id, document.account_id AS document_account_id, document.dataset_id AS document_dataset_id, document.upload_file_id AS document_upload_file_id, document.process_rule_id AS document_process_rule_id, document.batch AS document_batch, document.name AS document_name, document.position AS document_position, document.character_count AS document_character_count, document.token_count AS document_token_count, document.processing_started_at AS document_processing_started_at, document.parsing_completed_at AS document_parsing_completed_at, document.splitting_completed_at AS document_splitting_completed_at, document.indexing_completed_at AS document_indexing_completed_at, document.completed_at AS document_completed_at, document.stopped_at AS document_stopped_at, document.error AS document_error, document.enabled AS document_enabled, document.disabled_at AS document_disabled_at, document.status AS document_status, document.updated_at AS document_updated_at, document.created_at AS document_created_at 
FROM document 
WHERE document.id = %(pk_1)s::UUID
[2024-10-15 17:36:53,705.705] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00038s] {'pk_1': UUID('79cbfa87-6f28-4c68-a755-1db62e5a3b84')}
[2024-10-15 17:36:53,708.708] base.py -> _exec_single_context line:1903 [INFO]: SELECT upload_file.id AS upload_file_id, upload_file.account_id AS upload_file_account_id, upload_file.name AS upload_file_name, upload_file.key AS upload_file_key, upload_file.size AS upload_file_size, upload_file.extension AS upload_file_extension, upload_file.mime_type AS upload_file_mime_type, upload_file.hash AS upload_file_hash, upload_file.updated_at AS upload_file_updated_at, upload_file.created_at AS upload_file_created_at 
FROM upload_file 
WHERE upload_file.id = %(id_1)s::UUID
[2024-10-15 17:36:53,708.708] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00024s] {'id_1': UUID('1f913c05-8783-4de4-a2c7-c551fa17d0f6')}
[2024-10-15 17:36:53,710.710] base.py -> _exec_single_context line:1903 [INFO]: SELECT document.id AS document_id, document.account_id AS document_account_id, document.dataset_id AS document_dataset_id, document.upload_file_id AS document_upload_file_id, document.process_rule_id AS document_process_rule_id, document.batch AS document_batch, document.name AS document_name, document.position AS document_position, document.character_count AS document_character_count, document.token_count AS document_token_count, document.processing_started_at AS document_processing_started_at, document.parsing_completed_at AS document_parsing_completed_at, document.splitting_completed_at AS document_splitting_completed_at, document.indexing_completed_at AS document_indexing_completed_at, document.completed_at AS document_completed_at, document.stopped_at AS document_stopped_at, document.error AS document_error, document.enabled AS document_enabled, document.disabled_at AS document_disabled_at, document.status AS document_status, document.updated_at AS document_updated_at, document.created_at AS document_created_at 
FROM document 
WHERE document.id = %(pk_1)s::UUID
[2024-10-15 17:36:53,710.710] base.py -> _exec_single_context line:1908 [INFO]: [cached since 0.004933s ago] {'pk_1': UUID('4b4dbd64-4737-4c66-9a45-c6d9463e6e53')}
[2024-10-15 17:36:53,710.710] base.py -> _exec_single_context line:1903 [INFO]: SELECT upload_file.id AS upload_file_id, upload_file.account_id AS upload_file_account_id, upload_file.name AS upload_file_name, upload_file.key AS upload_file_key, upload_file.size AS upload_file_size, upload_file.extension AS upload_file_extension, upload_file.mime_type AS upload_file_mime_type, upload_file.hash AS upload_file_hash, upload_file.updated_at AS upload_file_updated_at, upload_file.created_at AS upload_file_created_at 
FROM upload_file 
WHERE upload_file.id = %(id_1)s::UUID
[2024-10-15 17:36:53,710.710] base.py -> _exec_single_context line:1908 [INFO]: [cached since 0.003194s ago] {'id_1': UUID('1f913c05-8783-4de4-a2c7-c551fa17d0f6')}
[2024-10-15 17:36:53,712.712] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-10-15 17:36:53,713.713] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 17:36:53] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/hit HTTP/1.1" 200 -
[2024-10-15 20:58:32,599.599] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 20:58:33,178.178] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 20:58:38,179.179] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 20:58:38,182.182] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 20:59:02,685.685] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 20:59:03,004.004] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 20:59:08,169.169] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 20:59:08,173.173] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 20:59:40,876.876] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\pkg\\response\\__init__.py', reloading
[2024-10-15 20:59:41,186.186] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 20:59:46,153.153] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 20:59:46,156.156] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 20:59:59,215.215] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 20:59:59,538.538] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:00:04,672.672] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:00:04,676.676] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:00:27,320.320] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:00:27,667.667] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:00:32,615.615] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:00:32,617.617] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:00:41,028.028] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:00:41,377.377] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:00:46,372.372] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:00:46,375.375] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:02:39,954.954] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:02:40,285.285] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:02:45,208.208] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:02:45,209.209] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:04:21,411.411] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:04:21,746.746] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:04:26,512.512] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:04:26,515.515] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:04:38,441.441] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:04:38,761.761] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:04:43,697.697] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:04:43,701.701] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:04:46,355.355] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:04:46,706.706] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:04:51,582.582] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:04:51,584.584] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:04:59,915.915] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:05:00,262.262] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:05:05,231.231] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:05:05,233.233] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:05:20,492.492] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\__init__.py', reloading
[2024-10-15 21:05:20,814.814] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:05:25,598.598] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:05:25,600.600] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:07:18,902.902] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\router\\router.py', reloading
[2024-10-15 21:07:19,242.242] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:07:24,303.303] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:07:24,306.306] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 139-858-996
[2024-10-15 21:07:30,607.607] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:07:30] "[35m[1mGET /conversations HTTP/1.1[0m" 500 -
[2024-10-15 21:07:30,829.829] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:07:30] "GET /conversations?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2024-10-15 21:07:30,829.829] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:07:30] "GET /conversations?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2024-10-15 21:07:31,150.150] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:07:31] "GET /conversations?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2024-10-15 21:07:31,402.402] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:07:31] "[36mGET /conversations?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-10-15 21:07:46,373.373] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:07:46,701.701] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:07:51,515.515] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:07:51,517.517] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 139-858-996
[2024-10-15 21:07:57,578.578] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 21:07:57,888.888] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:08:02,785.785] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:08:02,787.787] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 139-858-996
[2024-10-15 21:08:04,255.255] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\router\\router.py', reloading
[2024-10-15 21:08:04,610.610] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 21:08:09,652.652] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 21:08:09,655.655] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 21:08:09,806.806] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 21:08:09,822.822] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:09] "[35m[1mGET /conversations HTTP/1.1[0m" 500 -
[2024-10-15 21:08:09,961.961] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:09] "[36mGET /conversations?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2024-10-15 21:08:09,962.962] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:09] "[36mGET /conversations?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2024-10-15 21:08:10,277.277] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:10] "[36mGET /conversations?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-10-15 21:08:10,528.528] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:10] "[36mGET /conversations?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-10-15 21:08:36,253.253] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:36] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 21:08:36,625.625] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 21:08:36,634.634] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:08:36] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2024-10-15 21:16:24,108.108] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:16:24] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 21:16:24,595.595] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 21:16:24,697.697] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:16:24] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2024-10-15 21:25:03,720.720] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:25:03] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 21:25:04,165.165] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 21:25:04,198.198] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 21:25:04] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2024-10-15 22:37:46,576.576] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 22:37:46,968.968] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 22:37:51,966.966] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 22:37:51,969.969] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 22:37:53,370.370] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 22:37:53,755.755] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 22:37:58,413.413] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 22:37:58,415.415] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 22:37:59,438.438] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:37:59] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 22:37:59,937.937] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 22:37:59,950.950] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:37:59] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2024-10-15 22:38:08,459.459] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:38:08] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 22:38:26,775.775] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 22:38:27,180.180] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 22:38:32,091.091] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 22:38:32,094.094] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 22:38:33,207.207] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:38:33] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 22:38:58,017.017] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:38:58] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 22:38:58,486.486] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 22:38:58,516.516] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:38:58] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2024-10-15 22:53:02,982.982] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:53:02] "GET /conversions HTTP/1.1" 200 -
[2024-10-15 22:53:03,495.495] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-15 22:53:03,576.576] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 22:53:03] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2024-10-15 23:33:19,264.264] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:33:19,626.626] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:33:24,615.615] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:33:24,617.617] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:33:27,261.261] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:33:27,645.645] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:33:32,238.238] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:33:32,241.241] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:34:45,447.447] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:34:45,751.751] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:34:50,528.528] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:34:50,531.531] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:36:45,373.373] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:36:45,678.678] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:36:50,365.365] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:36:50,369.369] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:37:25,417.417] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:37:25,756.756] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:38:35,692.692] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:38:43,666.666] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:39:15,623.623] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:39:31,645.645] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:39:56,856.856] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:40:52,964.964] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:41:07,879.879] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:41:12,508.508] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:41:12,511.511] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:41:48,771.771] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:41:49,105.105] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:42:12,896.896] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:42:19,631.631] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:42:24,627.627] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:42:24,631.631] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:42:27,328.328] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:42:27,660.660] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:42:32,731.731] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:42:32,735.735] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:42:37,681.681] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:42:38,083.083] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:42:42,774.774] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:42:42,777.777] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:43:01,646.646] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:43:01,978.978] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:43:06,724.724] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:43:06,726.726] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:43:24,333.333] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:43:24,690.690] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:43:29,332.332] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:43:29,336.336] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:47:03,388.388] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:47:03,724.724] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:48:17,999.999] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:48:22,599.599] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:48:22,603.603] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:48:50,722.722] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:48:51,055.055] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:48:55,912.912] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:48:55,915.915] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:49:07,817.817] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:49:08,156.156] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:49:12,973.973] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:49:12,977.977] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:50:03,437.437] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-10-15 23:50:03,438.438] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-10-15 23:50:03,439.439] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:50:08,412.412] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:50:08,416.416] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:52:32,315.315] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:52:32,688.688] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:52:37,387.387] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:52:37,390.390] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:53:14,914.914] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:53:15,248.248] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:53:19,983.983] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:53:19,986.986] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:54:04,326.326] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:54:04,759.759] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:54:09,560.560] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:54:09,563.563] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:55:11,338.338] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:55:11,674.674] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:55:16,366.366] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:55:16,369.369] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:56:28,798.798] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:56:29,143.143] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:56:33,711.711] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:56:38,719.719] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:56:38,722.722] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:57:11,645.645] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:57:12,045.045] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:57:16,791.791] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:57:16,794.794] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:57:43,834.834] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:57:44,181.181] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:57:49,453.453] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:57:49,456.456] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:57:58,980.980] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:57:59,328.328] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:58:05,667.667] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:58:05,670.670] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:58:29,121.121] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:58:29,427.427] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:58:34,149.149] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:58:34,152.152] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:58:36,724.724] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:58:37,029.029] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:58:43,168.168] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:58:43,171.171] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:58:44,192.192] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 23:58:44] "GET /conversions?query=你能简单介绍下什么是LLM么、 HTTP/1.1" 200 -
[2024-10-15 23:59:07,473.473] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\conversation_handler.py', reloading
[2024-10-15 23:59:07,785.785] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-10-15 23:59:12,532.532] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-10-15 23:59:12,534.534] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-10-15 23:59:14,406.406] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [15/Oct/2024 23:59:14] "GET /conversions?query=你能简单介绍下什么是LLM么、 HTTP/1.1" 200 -
[2024-10-15 23:59:23,732.732] client.py -> info line:652 [WARNING]: Failed to get info from https://api.smith.langchain.com: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='api.smith.langchain.com', port=443): Read timed out. (read timeout=10.0)"))
